# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deneme',
        ),
    ]
