# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_auto_20161108_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='id',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AlterField(
            model_name='destination',
            name='coral_code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='coral_code',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
