# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp1', '0007_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pax_count',
            field=models.IntegerField(null=True),
        ),
    ]
