# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp1', '0009_booking_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='hotel_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
