# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('myapp1', '0010_booking_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkin',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='checkout',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
